### ISSUE TITLE
BUG: crystal spec fails when cnf-conformance repo directory is named differently

### ISSUE THREAD

**Issue by agentpoyo** [cncf/cnf-conformance#239]
After `shards install` step, setting KUBECONFIG env file export, `crystal spec` fails if the directory is not named cnf-conformance 

```
pair@cnfdev03:~/workspace/drew/cnf-conformance-test1$ crystal spec                      
Building ./cnf-conformance
Showing last frame. Use --error-trace for full trace.
In lib/halite/src/halite/features/logging.cr:1:1
 1 | require "log"
     ^
Error: can't find file 'log'
If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
crystal build failed!
Finished in 589.29 milliseconds
0 examples, 0 failures, 0 errors, 0 pending
Unhandled exception: crystal build failed in spec_helper (Exception)
  from spec/spec_helper.cr:10:4 in '__crystal_main'
  from /usr/local/depot/crystal-0.33.0-1/share/crystal/src/crystal/main.cr:106:5 in 'main_user_code'
  from /usr/local/depot/crystal-0.33.0-1/share/crystal/src/crystal/main.cr:92:7 in 'main'
  from /usr/local/depot/crystal-0.33.0-1/share/crystal/src/crystal/main.cr:115:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

To recreate failure with name other than cnf-conformance:

1. Clone repo with cnf-conformance-test1 (or any other name then cnf-conformance).  `git clone https://github.com/cncf/cnf-conformance.git cnf-conformance-test1`
2. Go into that directory `cd cnf- conformance-test1`
3. Export KUBECONFIG to your kubeconfig file with path
4. Run `shards install`
5. Run specs `crystal spec`

**Comment by nupejosh** [comment]
I still saw errors even though the halite shard was set to 0.10.4. The issue in this case was an incorrect crystal version being 0.31.1. I've since updated the shard.yml to declare the crystal version 0.33.0; this should ensure that the developer uses the correct version of crystal. 

If you're having trouble installing the correct version of crystal on your box, I've had great success with the crystal version manager [crenv](https://github.com/crenv/crenv) on ubuntu 14. -crenv is not a requirement

**Comment by taylor** [comment]
@nupejosh the crystal version manager sounds like a good thing for the INSTALL docs.

cc: @lixuna

**Comment by taylor** [comment]
Closing as invalid.  Issue was crystal version #226

**Comment by taylor** [comment]
Effort estimate: 2pts
