### ISSUE TITLE
[BUG] Unable to set-up example CNFs using release 0.9.19

### ISSUE THREAD

**Issue by clementnuss** [cncf/cnf-conformance#571]
**Describe the bug**
When trying to use the binary (`v.0.9.19`) and to setup a CNF, I receive the following error:

```
❯ ./cnf-conformance -l debug cnf_setup cnf-config=$(pwd)/example-cnfs/envoy/cnf-conformance.yml
I, [2021-01-19 01:29:19 -08:00 #755639]  INFO -- cnf-conformance: Results file
I, [2021-01-19 01:29:19 -08:00 #755639]  INFO -- cnf-conformance: file exists?:false
Successfully created directories for cnf-conformance
I, [2021-01-19 01:29:19 -08:00 #755639]  INFO -- cnf-conformance: helm_v3?: Regex::MatchData("BuildInfo{Version:\"v3.2.4\", GitCommit:\"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688\", GitTreeState:\"clean\", GoVersion:\"go1.13.12\"" 1:"v3.2.4" 2:"2.")
../../../../../usr/share/crystal/src/indexable.cr:588:11 in 'from_file'
../../../../../workspace/src/tasks/utils/cnf_manager.cr:157:21 in 'sample_setup_args'
../../../../../workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
../../../../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Not found config file `cnf-conformance` in `[".//mnt/ssd/cnf_conformance/tmp/v0919/example-cnfs/envoy"]`
❯
```

**To Reproduce**
1. Download version v0.9.19
2. Clone the Github repo and copy the `example-cnfs` folder nearby
3. Try to setup the `coredns` CNF: `./cnf-conformance cnf_setup cnf-config=$(pwd)/sample-cnfs/sample_coredns/cnf-conformance.yaml`
4. You will have an error

**Expected behavior**
With the latest binary (nightly), the same command works perfectly. 

**Device (please complete the following information):**
Tried this issue on two completely different clusters and Linux environments.

**Comment by agentpoyo** [comment]
Hello clementnuss,

You are missing the command `cnf-conformance setup` but the errors you are seeing do make sense given that there has been a lot of code changes since this release and using the latest code with example configs might produce undesirable results.

However, I was able to reproduce the error you are seeing.

Seems that if `$(pwd)` is used in the cnf-config path, that is causing the error seen. I am also able to reproduce this by doing the full path to the cnf-conformance.yml as well. `cnf-conformance` appears to want the path in relation to where it is located:

This works for me using the 0.9.19 binary installed via curl without `pwd` or the full path:
`cnf-conformance cnf_setup cnf-config=./example-cnfs/coredns/cnf-conformance.yml`

I did however run into another issue using this release by using the latest example configs.

The latest config file is missing helm_directory so it errors out and will complain that `helm_directory` isn't found. After adding helm_directory in the config, it successfully runs coredns (the example I used) onto my cluster but this is expected as the later code handles the new configs where helm_directory is not needed or required.

The 0.9.19 binary was built in mid December. I cannot find any references to updates of handling the absolute path and relative path in the cnf-config path but I can only assume this error was caught previously and fixed for the `$(pwd)` in the config path since it's not reproducible in the latest builds.

We should have a new stable build in the next few days that should fix most if not all of these errors you are seeing.

**Comment by clementnuss** [comment]
Thanks for checking that. I had run `setup` a few days ago but it didn't change the result.
Let's wait until the next stable build, then I'll do the same test and we can close it, if you agree.

**Comment by agentpoyo** [comment]
@clementnuss 

https://github.com/cncf/cnf-conformance/releases/tag/v1.10.0 was just released yesterday. So feel free to proceed with tests with this latest stable.

**Comment by clementnuss** [comment]
Hello,
I have just downloaded the latest release and can confirm that the bug is fixed!
Thanks for the rapid update.
