### ISSUE TITLE
[Research] Test running the test suite against a CNF using K8s secrets with a password protected vanilla Docker Registry

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-conformance#606]
**Is your feature request related to a problem? Please describe.**
The test suite has not be run against CNFs which have images on vanilla Docker Registry. Only those on Docker Hub.

**Describe the solution you'd like**
Run the test suite against a CNF with images hosted on a password protected, self-hosted, vanilla Docker Registry.

**Additional context**
Reference: 
- https://docs.docker.com/registry/
- https://docs.docker.com/registry/introduction/
- https://docs.docker.com/engine/reference/commandline/login/#login-to-a-self-hosted-registry
- [Support running the test suite against a CNF using a username/password protected Docker Hub #594](https://github.com/cncf/cnf-conformance/issues/594)

**Comment by lixuna** [comment]
### DRAFT - based on #594

---
### Documentation is updated:
- [ ] On https://github.com/cncf/cnf-conformance/blob/master/INSTALL.md, I can see information about private registry use with links to K8s docs


###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update example CNFs cnf-conformance.yml, if needed
- [ ] continue, If there is an update to cnf-conformance.yml
- [ ] for each CNF Example
- [ ] Update the example CNF's cnf-conformance.yml to include the new changes
- [ ] Update the example CNF's README if needed
- [ ] Test the example CNF following it's README

### Update yml validator, if needed
- [ ] N/A


### I would expect a CNF that is stored in a password protected Docker Hub repository to not have unexpected failures (caused by access issues) when running the `reasonable_image_size` test
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_private_registry/cnf-conformance.yml`
- [ ]  Run  `./cnf-conformance reasonable_image_size`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test

### I would expect a CNF that is stored in a password protected Docker Hub repository to not have unexpected failures (caused by access issues) when running the `workload` command
- [ ]  Follow common steps above
- [ ]  Prepare the test suite to use the CNF by running: `./cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_private_registry/cnf-conformance.yml`
- [ ]  Run  `./cnf-conformance workload`
- [ ]  I expect to see the output from the test
- [ ]  I expect to see PASSED for the test


### Screenshots of all command and workload command output
- [ ] I can see a screenshot testing the `image_size` test with a CNF in a private Docker Hub repository
- [ ] I can see a screenshot testing the `workload` test with a CNF in a private Docker Hub repository

**Comment by lixuna** [comment]
DRAFT: Level of effort in pts: 0,1,2,3,5,8,13,21: 
---

- @denverwilliams 
- @wavell 
- @williscool 
- @agentpoyo 
- @taylor 
- @lixuna

**Comment by taylor** [comment]
MVP items
---

New documentation: Using a private self-hosted Docker Registry with the CNF Test Suite
   - Part of INSTALL or new markdown doc

New example CNF for private docker registry. Test a known good example CNF using a self-hosted private Docker Registry
   - Make the configs and templates generic to support Docker Registry with credentials passed as environment variables
   - Cnf-conformance.yaml
   - CoreDNS modified Helm Chart
   - Add information about the example CNF in its README and what its specific purpose is and how its different from default ones (if it is a copy)
  - Upload the CoreDNS image to the registry
  - Create an example or use existing example CNF with cnf-conformance.yml and Helm chart to use with the registry CoreDNS

Manually run all workload tests against a CNF with images in the private self-hosted Docker Registry

Support K8s secrets for K8s images hosted on a private registry
  - other methods of configuration not supported at this time.

**Comment by agentpoyo** [comment]
Here's the workaround in getting CA certificates working using KIND clusters when you need to import CA root certificates that are imported on the OS level:

```
$ #kind create cluster --name kind --config=cluster.conf --kubeconfig ./kind.conf                                                                                                      
$ cat cluster.conf 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # This option mounts the host docker registry folder into
    # the control-plane node, allowing containerd to access them. 
    extraMounts:
      - containerPath: /etc/ssl/certs
        hostPath: /etc/ssl/certs
      - containerPath: /usr/share/ca-certificates/extra/
        hostPath: /usr/share/ca-certificates/extra/
pair@cnfdev03:~$ kind create cluster --name kind --config=cluster.conf --kubeconfig ./kind.conf
```
