### ISSUE TITLE
[Feature] If sandbox (./cnfs) directory is empty, discontinue tests

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-conformance#620]
**Is your feature request related to a problem? Please describe.**
The test suite continues to run in an odd manner if there are no cnfs installed in the ./cnfs directory

**Describe the solution you'd like**
If sandbox (./cnfs) directory is empty, discontinue tests

**Additional context**
![image](https://user-images.githubusercontent.com/29548/108561185-68f4e080-72c3-11eb-9a16-6b96233d4971.png)

**Comment by agentpoyo** [comment]
### Acceptance Criteria

---
###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the tests

### Update documentation 
- [ ] n/a

### Update Prerequisite checker
- [ ] N/A 

### Update yml validator, if needed
- [ ] n/a

## Show message on console output for remediation

### When cnfs/ directory is empty, discontinue tests with clean output on reason/finding:
- [ ] Follow common steps above
- [ ] Run ./cnf-conformance  workload
- [ ] I expect to see the output from the test
- [ ] I would expect to see a message that the tests will not run due to no cnf in the cnfs/ directory.

### Screenshots of all command and workload command output
- [ ] I can see a screenshot from output to discontinue test since cnfs/ directory is empty.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113048161-d4a25700-9167-11eb-8a91-b189621ab200.png)
