### ISSUE TITLE
[Feature] Remove wget as a cnf-conformance dependency.

### ISSUE THREAD

**Issue by denverwilliams** [cncf/cnf-conformance#679]
[Feature] Remove wget as a cnf-conformance dependency. Switch to using a crystal library or curl instead.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agentpoyo** [comment]
### Acceptance Criteria for peer review 
---
### Documentation is updated:
- [x] n/a

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [x]  Run `shards install`

### Spec test should pass
- [x]  Run `crystal spec`
- [x]  I expect to see PASSED for the tests

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect that the cnf-conformance.yml uses `allowlist` instead of `whitelist` and passes tests with no errors in output related to the allow_list:
- [x]  Follow common steps above
- [ ] Run `cnf_setup` should not output any requirements of wget in the output.
- [x]  Setup an example cnf: `cnf-conformance cnf_setup cnf-config=./sample-cnfs/sample_coredns_cnf/cnf-conformance.yml`
- [x]  Prepare the test suite to use the CNF by running: `./cnf-conformance workload`
- [x]  I expect to see PASSED for tests that pass and no errors related to `wget`

### Screenshots of all command and workload command output
- [x] I can see a screenshot of example output of passed tests with no errors related to wget.

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113338989-799b6c00-92ef-11eb-9e4f-c36bb3501f1a.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/113341163-75248280-92f2-11eb-9744-22bbae89bda3.png)
