### ISSUE TITLE
Installable Test: Does the CNF deploy successfully using Helm?

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#69]
[Acceptance Criteria](https://github.com/cncf/cnf-conformance/issues/69#issuecomment-595320871)
---

### Installable Test: Does the CNF deploy successfully using Helm?

EPIC: CNF Conformance Test Suite

Release: vN.N.N

Test Category: Installable and Upgradeable Tests

Type of test (static or runtime) = Runtime

- [x]  example code: #65 
- [x] [Brainstorming MVP ](https://hackmd.io/KWG0-fdYQ0u_EluagKISCg?view)

---

**Environment set up tasks:**

**Upstream tool set up tasks: (conformance suite + upstream tools)**
- N/A

**CNF setup Tasks** 

**Sample CNF tasks:**

**Code implementation tasks:**
- [ ] 

**Documentation tasks:**
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md) if needed 
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) if needed 
- [ ] Update [installation instructions](https://github.com/cncf/cnf-conformance#installation)  if needed 

**QA tasks**

Dev Review: 
- [x] walk through A/C
- [x] do you get the expected result?
- [x] if yes, 
   - [x] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request

**Comment by taylor** [comment]
Decisions to be made for the first iteration of this test: 
- pass helm arguments or not 
- support remote helm chart
- support local helm chart (via path)

**Comment by lixuna** [comment]
### (Draft) Acceptance Criteria: https://hackmd.io/i9c7RkzVTdKRO9OrKahGIA?sync=&type=

**Comment by taylor** [comment]
Brainstorming MVP https://hackmd.io/KWG0-fdYQ0u_EluagKISCg?view

**Comment by lixuna** [comment]
Level of effort in pts: 0, 1, 2, 3, 5, 8, 13, 21 = 5 pts
---

@taylor 5 pts
@denverwilliams 5 pts
@lixuna 5 pts

**Comment by nupejosh** [comment]
@wavell @denverwilliams is this cli for the AC correct here - 
`crystal src/cnf-conformance.cr installability ./cnf-conformance`? 
I've attempted several other variations with cnf-path/yml-file= etc, but all fail. Was this `installability` command ever working on the develop branch?

**Comment by taylor** [comment]
@nupejosh it looks like it should use yml-file as the argument with the yaml file as the value for that arg  https://github.com/cncf/cnf-conformance/commit/eda3ef5f174acd3429c039a589d05044bbefb97b#diff-3efacef5b2f53a034b12e746308b5d8aR16

Try:
- `crystal src/cnf-conformance.cr helm_deploy yml-file=./cnf-conformance.yml`
- or
- `crystal src/cnf-conformance.cr helm_deploy yml-file=./cnf-conformance.yml verbose`


@nupejosh, @wavell I'm not sure if the installability category task passes the args to the test.  See- https://github.com/cncf/cnf-conformance/blob/develop/src/tasks/installability.cr#L8

**Comment by taylor** [comment]
helm_deploy should be added as a dependent test in installability task:

```
task "installability", ["install_script_helm", "helm_chart_valid", "helm_chart_published"] do |_, args|
end

desc "Will the CNF install using helm with helm_deploy?"
task "helm_deploy" do |_, args|
```
https://github.com/cncf/cnf-conformance/blob/develop/src/tasks/installability.cr#L8-L12

**Comment by wavell** [comment]
#69

https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md

The CNF Conformance suite will check for usage of standard, in-band deployment tools such as Helm (version 3) charts. The Conformance suite checks this by:
Testing if the install script uses Helm v3
Testing if the CNF is published to a public helm chart repository.
Testing if the Helm chart is valid (e.g. using the helm linter)
Testing if the CNF can perform a rolling update (i.e. kubectl rolling update)

Add `Testing if the Helm chart installs`

https://github.com/cncf/cnf-conformance/blob/master/USAGE.md

Installable and Upgradeable Tests
✔️ To run all installability tests
crystal src/cnf-conformance.cr installability
(PoC) Test if the install script uses Helm v3
crystal src/cnf-conformance.cr install_script_helm
✔️ Test if the Helm chart is published
crystal src/cnf-conformance.cr helm_chart_published

Add `crystal src/cnf-conformance.cr helm_deploy`



A/C

`crystal src/cnf-conformance.cr helm_deploy ./cnf-conformance.yml`
doesn't work because there is no ./cnf-conformance.yml
- yml needs to be something else

`crystal src/cnf-conformance.cr helm_deploy sample-cnfs/sample-coredns-cnf/cnf-conformance.yml`

doesn't work.  got:
```
find: `cnfs/*': No such file or directory
No cnf_conformance.yml found! Did you run the setup task?
src/tasks/utils/sample_utils.cr:29:7 in 'get_parsed_cnf_conformance_yml'
src/tasks/installability.cr:15:14 in '->'
lib/sam/src/sam/task.cr:255:3 in 'call'
lib/sam/src/sam.cr:43:5 in 'invoke'
lib/sam/src/sam.cr:77:7 in 'process_tasks'
lib/sam/src/sam.cr:56:7 in 'help'
src/cnf-conformance.cr:22:1 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:106:5 in 'main_user_code'
/usr/share/crystal/src/crystal/main.cr:92:7 in 'main'
/usr/share/crystal/src/crystal/main.cr:115:3 in 'main'
__libc_start_main
???
???
```

ran >> `crystal src/cnf-conformance.cr cnf_setup cnf-path=sample-cnfs/sample-coredns-cnf`

then >> `crystal src/cnf-conformance.cr helm_deploy sample-cnfs/sample-coredns-cnf/cnf-conformance.yml`

got 

```
 crystal src/cnf-conformance.cr helm_deploy sample-cnfs/sample-coredns-cnf/cnf-conformance.yml
Error: cannot re-use a name that is still in use
FAILURE: Helm deploy failed
```

`cp -rf example-cnfs/coredns cnfs/coredns`
`crystal src/cnf-conformance.cr helm_deploy cnfs/coredns/cnf-conformance.yml`
got
`PASSED: Helm deploy successful`
`crystal src/cnf-conformance.cr installability cnfs/coredns/cnf-conformance.yml `

gave me
`Error: cannot re-use a name that is still in use`

ran 
`crystal src/cnf-conformance.cr cleanup `

then 
`kubectl get pods`
returned
```
NAME                                     READY   STATUS    RESTARTS   AGE
coredns-coredns-665dfdd658-mw7jc         1/1     Running   0          3m9s
```

(still had a coredns-coredns deployment)

ran 
`crystal src/cnf-conformance.cr cleanup force=true'                                                                                            returned                                                                                        
````/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
/home/pair/src/watson/cncf/cnf-conformance/tools/helm/linux-amd64/helm
[pair@dev:~/src/watson/cncf/cnf-conformance] 
☺ ➔  kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
dozing-turkey-coredns-55f96696d7-8tkxm   1/1     Running   0          13d
````

No more coredns-coredns deployment

ran
`crystal src/cnf-conformance.cr installability cnfs/coredns/cnf-conformance.yml`

got
```
PASSED (by default): No install script provided
Successfully created directories for cnf-conformance
ls: cannot access /home/pair/src/watson/cncf/cnf-conformance/cnfs/coredns/cnfs/coredns/helm_chart/coredns: No such file or directory
Error: 1 chart(s) linted, 1 chart(s) failed
FAILURE: Helm Chart cnfs/coredns/helm_chart/coredns Lint Failed
PASSED: Published Helm Chart Found
PASSED: Helm deploy successful
````

Helm deploy was successfull


ran `rm -rf cnfs/coredns`
`crystal spec --tag 'helm' -v`

Finished in 18.82 seconds
4 examples, 0 failures, 0 errors, 0 pending

***should update the above a/c to reflect what is needed***

**Comment by lixuna** [comment]
@denverwilliams @wavell @taylor what’s remaining on this test?

**Comment by lixuna** [comment]
@taylor @denverwilliams can you please peer review this issue?
