### ISSUE TITLE
[Documentation] update USAGE.md to note if test is completed as Recreatable, a Proof of Concept or To Do

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-conformance#95]
### [Documentation] update USAGE.md to note if test is completed as Recreatable, a Proof of Concept or To Do

*Short Description:* 
- The usage doc can be used to see the status of tests in progress
- CNF Conformance tests are created in 2 phases: Proof of Concept (PoC) and Recreatable Tests for test developers. 
- Proof of Concept tests are created to determine what tool can be used and how it can be used (choosing least effort by default).
- Recreatable tests can be run by a developer to check the conformance of a CNF

*Tasks:*

- [x] review https://github.com/cncf/cnf-conformance/blob/master/USAGE.md
- [x] list tests that have Proof of Concept completed on `develop`
- [x] list tests that have Recreatable tests completed and integration tests pass on `master`
- [x] if test does not have a Proof of Concept and is not Recreatable, mark it as `To Do`
- [x] if test does have a Proof of Concept on `develop` and is not Recreatable, mark it as `PoC`
- [x] if test is Recreatable and integration tests pass on `master`, mark it with a ✔️ 
- [x] create draft
- [ ] peer review
- [ ] update draft, if needed
- [ ] merge to master

**Comment by lixuna** [comment]
Draft in https://hackmd.io/hH-0lLLZSESJ_3IXqinm0Q?sync=&type=

**Comment by taylor** [comment]
**Suggested workflow for updating status of a conformance test in the USAGE.md for ToDo**
1. When a new test idea is decided on but not yet started (no PoC or full test) 
2. Add the new test with ToDo the USAGE.md.
3. Create a PR and link the PR to any relevant github issue
4. Review and Merge PR

**Suggested workflow for updating status of a conformance test in the USAGE.md for PoC** 
1. After code is merged to master , passes all tests (automated or otherwise), and any human manual AC
2. Create a PR for updating the USAGE.md to change the status of the test to PoC  and link to the github issue
3. Review and Merge PR
4. Close issue

**Suggested workflow for updating status of a conformance test in the USAGE.md for** 
1. :heavy_check_mark: 
2. After code is merged to master , passes all tests (automated or otherwise), and any human manual AC
3. Create a PR for updating the USAGE.md to change the status of the test to :heavy_check_mark:  and link to the github issue
4. Review and Merge PR
5. Close issue
